### ISSUE TITLE
Component's ParentReference Access type can't be defined

### ISSUE THREAD

**Issue by NOtherDev** [nhibernate/fluent-nhibernate#120]
In Fluent NHibernate 1.3 there's no way to set up Access property for Component's ParentReference option.

```
Component(x => x.Test, m =>
{
    m.ParentReference(c => c.Parent).Access.Field();
});
```

This code set access strategy for `x.Test` property. Setting access strategy for `c.Parent` is not possible.

See also: http://notherdev.blogspot.com/2012/01/mapping-by-code-component-and-odd-cases.html

**Comment by hazzik** [comment]
Added optional second argument 

```
Component(x => x.Test, m =>
{
    m.ParentReference(c => c.Parent, Access.Field);
});
```
