### ISSUE TITLE
OptimisticLock in HasMany/HasManyToMany broken

### ISSUE THREAD

**Issue by NOtherDev** [nhibernate/fluent-nhibernate#124]
In Fluent NHibernate 1.3, when trying to use `OptimisticLock` option in `HasMany`/`HasManyToMany` chain, it's not possible to set boolean value there, expected by NHibernate. Fluent NHibernate offers choosing one of options available only at entity level. Choosing any value results in `XML validation error` exception when creating session factory.

It is:

```
HasMany(x => x.Users).OptimisticLock.Version();
```

It should be:

```
HasMany(x => x.Users).OptimisticLock();
```

See also: http://notherdev.blogspot.com/2012/01/mapping-by-code-set-and-bag.html

**Comment by hazzik** [comment]
Was fixed in 5d225f89. Closing as obsolete.
