### ISSUE TITLE
PersistenceSpecification.Checkproperty

### ISSUE THREAD

**Issue by nsorochan** [nhibernate/fluent-nhibernate#138]
When I use the method in writing test cases. It fails if one of my properties is a double, and using Oracle as my datasource. 
my oracle field is defined as Number(6,2), my c# property is defined as a double.

If i set the property to 4.35, the number coming back is 4.34999......which is basically the same number, however, the checkproperty fails.

Any ideas?

**Comment by hazzik** [comment]
This is the Oracle's `NUMBER` problem. The `NUMBER` type does not conform to IEEE standard and not fully compatible to .NET's float/double. To overcome this problem use overload which accepts a custom `IEqualityComparer`. And implement fuzzy comparison with a precision.
