### ISSUE TITLE
Issue with new Configuration inserting records

### ISSUE THREAD

**Issue by CapnAndy-xx** [nhibernate/fluent-nhibernate#174]
I'm trying to use Fluent for a 400-series IBM iSeries server. I discovered that there are currently no configurations that use the DB2400 driver and dialect, so I created one and named it ISeriesConfiguration (and ISeriesConnectionString for the connection string class). To make it I just copied DB2Configuration and DB2ConnectionStringBuilder and changed the Driver/Dialect calls to DB2400Driver and DB2400Dialect. This works in all respects except for inserting/updating records. 

When I try to do that, I either get SQL error that it could not insert values [?,?,?](for Save) or that it could not go checking for a record with value ? (for SaveOrUpdate). When I do exactly the same thing except for a SqlServer2012 database, it works flawlessly. 

I think I missed something somewhere when I made my new classes. What would that be? I'll post any code you need.

**Comment by hazzik** [comment]
8 years later. No code. Closing.
