### ISSUE TITLE
Fluent NHibernate table-per-inheritance (TPH) mapping for multi class in the hierarchy

### ISSUE THREAD

**Issue by avolgin** [nhibernate/fluent-nhibernate#222]
Hello everyone,

I'm struggling with one Fluent NHibernate issue. I have following template of class structure in the my solution:

class OneClass
{
    public virtual string OneProp {get; set;}
}

class TwoClass : OneClass
{
     public virtual string TwoProp {get; set;}
}

class ThreeClass : TwoClass
{
     public virtual string ThreeProp {get; set;}
}

And I want to use table-per-inheritance hierarchy strategy for my classes for contains all data in one table in a database.

How it possible to do via Fluent NHibernate?

I have posted this question to StackOverflow too:
http://stackoverflow.com/questions/16563530/fluent-nhibernate-table-per-inheritance-tph-mapping-for-multi-class-in-the-hie

Sincerely,
Volgin Alexey

**Comment by hazzik** [comment]
Most likely similar to #410

**Comment by hazzik** [comment]
Sorry, it is late. But better late then never.

Ideally the solution which you've tried should work without issues. But, unfortunately, FNH does not support it. To make it work you need to implement IAutomappingConfiguration and override IsDiscriminated method. Something like this:

```csharp
class MyDefaultConfiguration : DefaultAutomappingConfiguration
{
    private readonly Type[] discriminatedTypes = new[]
    {
        typeof(OneClass), typeof(TwoClass), typeof(ThreeClass)
    };

    public override bool IsDiscriminated(Type type)
    {
        return discriminatedTypes.Contains(type) || base.IsDiscriminated(type);
    }
}
```

Then you can use this configuration in when you create your persistent model:

```csharp
AutoMap.AssemblyOf<OneClass>(new MyDefaultConfiguration())
````
