### ISSUE TITLE
Move to Ripple - latest version possible - and update the readme.md

### ISSUE THREAD

**Issue by chester89** [nhibernate/fluent-nhibernate#254]
<a href="https://github.com/darthfubumvc/ripple">Ripple</a> is a dependency management tool developed by Fubu team. It was built to ease the pain of using NuGet, especially it's hilarious "Enable package restore" command (frankly, I go nuts every time I have to download an earlier version of a package). 
Ripple is already in the repository - it's an old version from a year ago with some upgrades of mine. Now I'd like to have the newest version (v2 or v3, not really sure). 
Fubu guys have 2 options for Ripple - .NET executable and a Ruby gem. I would prefer the former, cause not every contributor has Ruby installed.
As I heard, it got a convert command that turns every package.config file in your solution into Ripple friendly format.
Also, when done, it would be wonderful to update Readme.md with instructions on how to build Fluent NHibernate source code using Ripple.

**Comment by hazzik** [comment]
Ripple is dead now, I believe, and FNH is using Cake. So closing as obsolete.
