### ISSUE TITLE
Add strongly typed OrderBy overload for collections mappings

### ISSUE THREAD

**Issue by mwpowellhtx** [nhibernate/fluent-nhibernate#289]
Might benefit from having AsBag, and/or other collection extensions, configure based on property expressions.

Proposed extension method signature would look something like this:

``` C#
public static OneToManyPart<T> AsBag<T>(this OneToManyPart<T> part,
    Expression<Func<T, object>> orderBy)
{
    // ...
}
```

**Comment by rtu-dev** [comment]
Hello friend, could you help me understand how the AsBag method works.
If you can give me some material, I appreciate it.

**Comment by hazzik** [comment]
The syntax is:
```csharp
m.HasMany(x => x.BagOfChildren)
 .AsBag()
 .OrderBy(c => c.Name)
```
