### ISSUE TITLE
NHibernate 4 update - Cannot simultaneously fetch multiple bags

### ISSUE THREAD

**Issue by nomoresocks** [nhibernate/fluent-nhibernate#296]
I'm updating my current codebase to use NHibernate 4, and I've run into an issue with the fluent configuration on the current upgrade.  I have the following call to configure my mappings:

```
ISessionFactory _SF = Fluently.
        Configure(configuration).
        Cache(x => x.UseSecondLevelCache().UseQueryCache().ProviderClass<NHibernate.Caches.SysCache.SysCacheProvider>()).
        Mappings(m =>
        {
            m.FluentMappings.AddFromAssemblyOf<VenueLocationMap>().Conventions.Add(DefaultCascade.None());
            m.AutoMappings.Add(AutoMap.AssemblyOf<SMSGroup>(new AutomappingConfiguration())
                .Override<Communication>(x =>
                    {
                        x.References<Communicator>(y => y.PreviousMessage).Cascade.None();
                        x.References<Communicator>(y => y.CurrentMessage).Cascade.None();
                    })
                .Conventions.Add(DefaultCascade.All())
                );
        }).CurrentSessionContext<HybridWebSessionContext>().BuildSessionFactory();
```

When I run that, I get a `QueryException` stating `Cannot simultaneously fetch multiple bags`.  I'm sure this is the result of some kind of deprecation that occurred in NHibernate 4, but it's not clear what transition should be made to make my mappings work.  What is the recommended course of action for this upgrade?

**Comment by chester89** [comment]
I believe it's a common problem for both Hibernate and NHibernate. Try [this] (http://www.wenda.io/questions/5204085/hibernate-fetching-objects-collections-without-multiple-bags.html) or [that one] (http://stackoverflow.com/questions/2403868/error-cannot-simultaneously-fetch-multiple-bags-when-calling-configuration-bu)

**Comment by increddibelly** [comment]
Thanks. We're seeing this error too, since upgrading to NH4.

**Comment by chester89** [comment]
May be @hazzik can shed some light on that problem?

**Comment by masums** [comment]
we are getting same error (NHibernate.QueryException: Cannot simultaneously fetch multiple bags.) after upgrading NH into 4.0 but actually who is causing the problem NH4 or FluentNHibernate?

**Comment by masums** [comment]
Also @chester89 's given link is showing solution for xml mapping not for fluently mapping. How we can add outer-join="true" at fluent mapping?

**Comment by chester89** [comment]
As far as I remember, outer join can only be configured on a
PersistenceConfiguration level (e.g.
Fluently.Configure.Database(MsSqlConfiguration.MsSql2008.UseOuterJoins()...),
but not on a collection level. I'll add that to features list

2015-06-04 8:44 GMT+03:00 masums <notifications@github.com>:

> Also @chester89 <https://github.com/chester89> 's given link is showing
> solution for xml mapping not for fluently mapping. How we can add
> outer-join="true" at fluent mapping?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/296#issuecomment-108735100>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by zerokewl88** [comment]
Hi Guys - still having this issue now days.. is there a fix for Fluent Mapping at a Collection level.. without having to convert o ISet<T>

Thank you.

**Comment by flastowizka** [comment]
have a solution without convert to ISet ?

**Comment by mesutcakir** [comment]
I was having the same problem. Creating errors in mapping I checked the mapping of the models. I've detected problems in the section I use for Parent-Childs same object.

I'm using FluentMapping. The only place I had left was the room exploding. I've fixed it. (Fetch.Join() delete using.)

`
public class ItemObj{
                public virtual IList<ItemObj> Childs{   get;  set;  }
 }

//Problem Version
 HasMany(d => d.Childs)
                .KeyColumn("ParentId")
                .ForeignKeyConstraintName("FK_NAMe...")
                .LazyLoad()
                _.Fetch.Join()_ //Deleted.
                ;

**//WORKED Version
 HasMany(d => d.Childs)
                .KeyColumn("ParentId")
                .ForeignKeyConstraintName("FK_NAMe...")
                .LazyLoad()                
                ;**
`

**Comment by andrew-tam** [comment]
Hello, I'm upgrading a project to NHibernate 5.2 and using Fluent mappings. I'm experiencing this same error with a class map that includes a composite ID and two ManyToOnePart References. Has anyone found a resolution to this error? I've tried specifying .UseOuterJoin() on the Database configuration, but nothing I've tried has made any difference. Any help would be greatly appreciated.

**Comment by hazzik** [comment]
This is by design.
