### ISSUE TITLE
PostgreSQL Schema Name ToLower

### ISSUE THREAD

**Issue by sublime93** [nhibernate/fluent-nhibernate#302]
If a user has created a schema in posgres that has an upper case letter in it fluent will not see it as it seems to mark the mapped schema name to lower variant. 

The following exception is thrown when i have a schema name of "Internal". Within my map class i have also specified `Schema("Internal");`

`{"An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.\r\n\r\n"}`

Inner Exception:
`{"ERROR: 3F000: schema \"internal\" does not exist"}`

If i change the schema name within postgres to "internal" it works fine.

**Comment by chester89** [comment]
Can you post full code that reproduces this problem? I'll look into the code, but I'd like to be sure that after making some changes we don't break compatibility with other databases

**Comment by hazzik** [comment]
This is limitation of PostgreSQL, you need to quote the schema.
