### ISSUE TITLE
Can't map value object(component) as Id

### ISSUE THREAD

**Issue by kobbikobb** [nhibernate/fluent-nhibernate#318]
Is it possible to map a value object as a Id?

Here I am mapping a value object as component.

```
public class ProcessingCodeMap : ClassMap<ProcessingCode>
{
    public ProcessingCodeMap()
    {
        Component(x => x.Code, p => p.Map(x => x.Value).Not.Nullable());
        ... other properties
    }
}
```

**Comment by Trinition** [comment]
Yes!

I have a project where we use Int32 wrappers as our IDs in the domain, primarily to make accidental crossing of IDs impossible.  So I have a base class, BaseId, that wraps the Int32, and then specific subclasses for each distinct type of ID I have.

I followed information I found in the wild, http://darrell.mozingo.net/2009/02/10/generic-nhibernate-user-type-base-class/, to make my own NHibernate UserType for handling these sub-types.

Then in my fluent ClassMaps, I have to work-around a Fluent NHibernate limitation (see https://github.com/jagregory/fluent-nhibernate/issues/230).  Right now, you can't use .GeneratedBy().Identity() with a custom type.  FNH wrongly assumes you can only do that with a plain Int32, even though it absolutely is possible with a custom UserType.  So, my map looks like this:

```c#
            Id(x => x.Id, "CustomerID")
                //.GeneratedBy.Identity()
                .GeneratedBy.Custom("identity")//Identity() // TODO This overcomes a bug in FluentNHibernate that tries to force integral identity types when in fact NH supposrt custom types like ours; see https://github.com/jagregory/fluent-nhibernate/issues/230
                .CustomType<BaseIdUserType<CustomerId>>()
                .UnsavedValue(0);
```

**Comment by kobbikobb** [comment]
I don't need the auto-generation. The Id comes from the user.

How does this look?

    public class ProcessingCodeMap : ClassMap<ProcessingCode>
    {
        public ProcessingCodeMap()
        {
            Id(x => x.Code, "Code").Length(4).Not.Nullable()
                .CustomType<CodeType>();
        }
    }

    public class CodeType : BaseImmutableUserType<Code>
    {
        public override object NullSafeGet(IDataReader rs, string[] names, object owner)
        {
            var obj = (string)NHibernateUtil.String.NullSafeGet(rs, names[0]);
            if (obj == null) return null;
            return new Code(obj);
        }

        public override void NullSafeSet(IDbCommand cmd, object value, int index)
        {
            var code = value as Code;
            object valueToSet;

            if (code != null)
            {
                valueToSet = code.Value;
            }
            else
            {
                valueToSet = DBNull.Value;
            }

            NHibernateUtil.String.NullSafeSet(cmd, valueToSet, index);
        }

        public override SqlType[] SqlTypes
        {
            get
            {
                return new[]
			       	{
			       		SqlTypeFactory.GetString(4)
			       	};
            }
        }
    }

**Comment by hazzik** [comment]
The answer is to use `CompositeId` instead of `Component`:

```csharp
public class ProcessingCodeMap : ClassMap<ProcessingCode>
{
    public ProcessingCodeMap()
    {
        CompositeId(x => x.Code, p => p.KeyProperty(x => x.Value).Not.Nullable());
        //... other properties
    }
}
```
