### ISSUE TITLE
Cannot access schema when creating custom IJoinedSubclassConvention implementation

### ISSUE THREAD

**Issue by ivaylo5ev** [nhibernate/fluent-nhibernate#319]
Currently I am in need of implementing the `IJoinedSubclassConvention` where I need to override the schema, by deriving from the original schema name. The `IJoinedSubclassInstance` interface exposes a `Schema` method for that, but it does not allow you to access the current value of the schema.

For reference, it is possible when implementing `IClassConvention` to access the member `Schema` by the following line:
`var schema = ((IClassInspector) instance).Schema;`, where `instance` is the `IClassInstance` object.

Doing so with `IJoinedSubclassInstance` as follows:
`var schema = ((IJoinedSubclassInspector) instance).Schema;`
does not work, as there is no such property, nor it seems that the `IJoinedSubclassInstance` exposes that in any other way. Thus, I was forced to use reflection to get my thing done.

I think there should be a `Schema` property there, for the sake of consistency with the other convention interfaces which are applicable.

---

I am willing to personally provide a patch if you would agree such functionality is necessary in the future development of the project.

**Comment by chester89** [comment]
That would be great. How would you do it - adding a property/method to an interface?

**Comment by ivaylo5ev** [comment]
Yes, I plan to make the same thing that is present in the ClassInspector implementation - expose the `mapping.Schema` property
