### ISSUE TITLE
Enhance IPropertyInstance to detect automatically generated column names

### ISSUE THREAD

**Issue by fubar-coder** [nhibernate/fluent-nhibernate#322]
An enhancement of `IPropertyInstance` would be useful to detect the situation where the column name was generated automatically by fluent-nhibernate. This would allow a distinction in situations where the property name really equals to the column name and where the column name is automatically generated and has to be modified in a way that matches (most) of the databases convention.

I know that working with legacy databases are a PITA, but I have no chance to change the legacy database in question.

EDIT: The current workaround is using the column name `auto` instead which doesn't seem the ... right solution to me.

**Comment by hazzik** [comment]
This should work:

```csharp
public class PropertyNameConvention : IPropertyConventionAcceptance, IPropertyConvention
{
    public void Accept(IAcceptanceCriteria<IPropertyInspector> criteria)
    {
        criteria.Expect(c => c.Name, Is.Not.Set);
    }

    public void Apply(IPropertyInstance instance)
    {
        //TODO: Add your convention
    }
}
```

Sorry it took 7 years.
