### ISSUE TITLE
Unable to set field or property "Access" on nested components

### ISSUE THREAD

**Issue by fassadlr** [nhibernate/fluent-nhibernate#370]
As the heading states, I am unable to set Access on nested components. Consider the following scenario:
```

            Component(a => a.houses, b =>
            {
                b.Access.Field();
                b.HasMany(c => c.Tenants)
                    .AsSet()
                    .Cascade.AllDeleteOrphan()
                    .ForeignKeyConstraintName("fk_house_tenant")
                    .KeyColumn("houseid")
                    .Not.LazyLoad()
                    .Component(comp=> 
                    {
                        comp.Access.Field();
                    });
            });
```
comp.Access.Field(); is not available?

**Comment by chester89** [comment]
@fassadlr yes, I don't think that's supported. Don't exactly remember the reason now

**Comment by fassadlr** [comment]
@chester89 Hi Chester, any idea if this feature will be added? We are using this quite extensively in our HBMs and would like to fully migrate our mappings to Fluent.

Thanks in advance!

**Comment by hazzik** [comment]
In this scenario `comp` is a `composite-element` and it does not support access.

https://github.com/nhibernate/nhibernate-core/blob/9255435d3b9ce6f3260ef9ecef58d17c484d15c7/src/NHibernate/nhibernate-mapping.xsd#L289-L303

However, `nested-composite-element` should support access:

https://github.com/nhibernate/nhibernate-core/blob/9255435d3b9ce6f3260ef9ecef58d17c484d15c7/src/NHibernate/nhibernate-mapping.xsd#L998-L1014
