### ISSUE TITLE
Add comments to SetupConventionFinder and IConventionFinder

### ISSUE THREAD

**Issue by mwpowellhtx** [nhibernate/fluent-nhibernate#371]

**Comment by chester89** [comment]
@mwpowellhtx can you clarify? I'd welcome a PR, by the way

**Comment by mwpowellhtx** [comment]
@chester89  It's been a little while since I posted this and I can't recall precisely which avenue I was investigating. Perhaps something to do with a stronger convention based approach.

There are comments on the ``IConventionFinder``. However, ``SetupConventionFinder<TReturn>`` is another story altogether.

When I press *F12* to reference the class, documentation, etc, I get this:

```C#
public class SetupConventionFinder<TReturn> : IConventionFinder
{
    public SetupConventionFinder(TReturn container, IConventionFinder conventionFinder);

    public TReturn Add(Type type);
    public TReturn Add(params IConvention[] instances);
    public void Add(Type type, object instance);
    public TReturn Add<T>() where T : IConvention;
    public TReturn Add<T>(T instance) where T : IConvention;
    public TReturn AddAssembly(Assembly assembly);
    public TReturn AddFromAssemblyOf<T>();
    public TReturn AddSource(ITypeSource source);
    public IEnumerable<T> Find<T>() where T : IConvention;
    public TReturn Setup(Action<IConventionFinder> setupAction);
}
```

What is a ``TReturn``? And why does it also receive an ``IConventionFinder``? Referencing the ``SetupConventionFinder`` itself?

``T`` are apparently the ``IConvention``?

No, I'm not going to second guess the author(s) "intent" for this class. That's for the author(s) to speak to.

For starters.

Thank you...

**Comment by hazzik** [comment]
PR would be welcomed.
