### ISSUE TITLE
Add Port to MySQL ConnectionString builder

### ISSUE THREAD

**Issue by jrgcubano** [nhibernate/fluent-nhibernate#405]

**Comment by SkydivingAngel** [comment]
I made changes to the downloaded source code:

Changes made in **MySQLConnectionStringBuilder** Class:

Added:

		private string port = "3306";

Added:

		public MySQLConnectionStringBuilder Port(string port)
		{
			this.port = port;
			IsDirty = true;
			return this;
		}

Changed:

		protected internal override string Create()
		{
			var connectionString = base.Create();

			if (!string.IsNullOrEmpty(connectionString))
				return connectionString;

			var sb = new StringBuilder();

			sb.AppendFormat("Server={0};Database={1};User ID={2};Password={3};Port={4}", server, database, username, password, port);

			return sb.ToString();
		}

so it can be used this way:

		MySQLConfiguration connection01 = MySQLConfiguration.Standard
		.ConnectionString(c => c
		.Server("localhost")
		.Database(dbName)
		.Username("xxxx")
		.Password("yyyy")
		.Port("3308")
		)

Full Example:

    public class SessionFactoryCreator
    {
        public static ISessionFactory GetSession(string dbName = "Test", byte timeout = 10)
        {
            MySQLConfiguration connection = MySQLConfiguration.Standard
                .ConnectionString(c => c
                    .Server("localhost")
                    .Database(dbName)
                    .Username("xxx")
                    .Password("yyy")
                    .Port("3306")
                )
                .ShowSql().FormatSql();

            ISessionFactory sessionFactory = Fluently.Configure()
                .Database(connection)
                .Cache(cacheBuilder =>
                {
                    cacheBuilder.UseQueryCache();
                    cacheBuilder.UseSecondLevelCache().ProviderClass<NHibernate.Cache.HashtableCacheProvider>();
                })
                .Mappings(mapper =>
                {
                    mapper.FluentMappings.Add<FirstMap>();
                    mapper.FluentMappings.Add<SecondMap>();
                })
                .ExposeConfiguration(cfg =>
                {
                    cfg.SetProperty(NHibernate.Cfg.Environment.CommandTimeout, "180");
                    cfg.SetProperty(NHibernate.Cfg.Environment.ReleaseConnections, "after_transaction");
                    cfg.SetProperty(NHibernate.Cfg.Environment.BatchSize, "1000");
                    new SchemaUpdate(cfg).Execute(false, true);
                })
                .BuildSessionFactory();

            return sessionFactory;
        }
    }
