### ISSUE TITLE
Missing constructor exception when using subclass automapping

### ISSUE THREAD

**Issue by kYann** [nhibernate/fluent-nhibernate#418]
Hello,

When using subclass automapping, and setting the discriminated value, if the discriminated value is not a string the AutoSubClassPart object can't be created.

> System.MissingMethodException : Constructor on type 
> 'FluentNHibernate.Automapping.AutoSubClassPart`1 
> [[Something.Model.Sender, Something.Core, Version=1.0.0.0, 
> Culture=neutral, PublicKeyToken=null]]' not found. 

This is due to the fact that the AutoSubClassPart constructor takes a string as a discriminated value, if we give anything different than a string Activator.CreateInstance can't find the constructor.

https://github.com/nhibernate/fluent-nhibernate/blob/161ffa1fef09306126692760b1c5a194b8d5df01/src/FluentNHibernate/Automapping/AutoMapping.cs#L162-L175

```
public void Override(AutoMapping<Sender> mapping)
{
	mapping.DiscriminateSubClassesOnColumn("__type");
	mapping.SubClass<SpecialSender>(0);
}
```

**Comment by hazzik** [comment]
Inline Subclass definitions never worked with the AutoMapping<>. 

With #469 you can now set DiscriminatorValue on subclass:

```
public void Override(AutoMapping<SpecialSender> mapping)
{
	mapping.DiscriminatorValue(0);
}
```
