### ISSUE TITLE
Can't override key colum name in JoinedSubClass Automapping

### ISSUE THREAD

**Issue by jagregory** [nhibernate/fluent-nhibernate#42]
See: https://groups.google.com/forum/#!topic/fluent-nhibernate/xblilnwhGWE/discussion

**Comment by ltvan** [comment]
I used JoinedSubClassConvention to override key column name, but there is another headache issue that take me days to fix: do not use `ForeignKey.EndsWith("Id")`, otherwise the joined-subclass column always add a column named `<ParentClass>Id`.

**Comment by hazzik** [comment]
With #468 you can do following:

```
public class PersonMappingOverride : IAutoMappingOverride<Person>
{
    public void Override(AutoMapping<Employee> mapping)
    {
        mapping.KeyColumn("EmployeeID");
    }
}
```
