### ISSUE TITLE
Please create ability to map hidden collections 

### ISSUE THREAD

**Issue by megafetis** [nhibernate/fluent-nhibernate#428]
Please create ability to map hidden collections as in native mapping by code (Set("ProtectedList"))
Or possibility to add mappingByCode mappings to FluentConfiguration

OneToMany and ManyToMany

**Comment by megafetis** [comment]
I need it to cascade remove bidirectional assoiated relationships

**Comment by hazzik** [comment]
It is possible ans was always possible:

```csharp
HasMany(Reveal.Member<Entity, IEnumerable<Child>>("ProtectedList")).AsSet()
```
