### ISSUE TITLE
Version 2.1.2 don't work with NHibernate  5.2.4

### ISSUE THREAD

**Issue by masyaf** [nhibernate/fluent-nhibernate#430]
FluentNHibernate 2.1.2
NHibernate 5.2.4

FluentNHibernate does not work with a version of NHibernate

When you run an application and perform the insert procedure

An application throws an exception;

System.Exception: 'Can not make the file or assembly' NHibernate, Version = 5.1.0.0, Culture = neutral, PublicKeyToken = aa95f207798dfdb4 'or one of its dependencies. An assembly definition is not a reference to the assembly. (Exception from HRESULT: 0x80131040) '

Exception thrown: 'System.IO.FileLoadException' in InterCert.Infrastructure.Repository.dll
Exception posted: 'System.TypeInitializationException' in InterCert.Infrastructure.Repository.dll
Exception thrown: 'System.Exception' in InterCert.Model.Negocio.dll
An unhandled exception of type 'System.Exception' occurred in InterCert.Model.Negocio.dll
Can not load the file or assembly 'NHibernate, Version = 5.1.0.0, Culture = neutral, PublicKeyToken = aa95f207798dfdb4' or one of its dependencies. An assembly definition is not a reference to the assembly. (Exception from HRESULT: 0x80131040)

My SessionProvider
```
using System;
using FluentNHibernate.Cfg;
using FluentNHibernate.Cfg.Db;
using InterCert.Modelo.Entitdades;
using NHibernate;
using NHibernate.Tool.hbm2ddl;

namespace InterCert.Infraestrutura.Repositorio.NHibernate.Helpers
{
    internal class SessionProvider
    {
        private static ISessionFactory `_sessionFactory;`

        static SessionProvider()
        {

            _sessionFactory = Fluently.Configure()
              .Database(MsSqlConfiguration.MsSql2008
                .ConnectionString(c => c
                  .FromConnectionStringWithKey(InterCertGlobal.CONN_STRING))
                .ShowSql())
              .Mappings(m => m
                .FluentMappings.AddFromAssemblyOf<Estoque>())
               .ExposeConfiguration(cfg => new SchemaExport(cfg).Execute(true, true, false))
              .BuildSessionFactory();



        }

        public static ISessionFactory SessionFactory
        {
            get
            {
                return _sessionFactory;
            }
        }
    }
}



```

**Comment by achirun** [comment]
I have the same trouble when initializing from another project.

**Comment by kpinette** [comment]
I'm experiencing the same issue when trying to install a windows service that references FluentNHibernate 2.1.2. I have NHibernate 5.2.5 but it's looking for 5.1.0.0 even with a binding redirect set in my app.config. Is anyone planning on addressing this?

**Comment by danilobreda** [comment]
#429

**Comment by Gener4tor** [comment]
Ive got the same problem. Does anyone has a workaround for this?

**Comment by kpinette** [comment]
I had to downgrade to NHibernate 5.1.5. Hasn't been an issue, but we don't use NH heavily in this project. I'd have concerns with some of our others.

**Comment by Gener4tor** [comment]
@kpinette: Thanks. Downgrading to NHibernate 5.1.5 worked for me too...

**Comment by kpstolk** [comment]
@kpinette A binding redirect does work for me:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="NHibernate" publicKeyToken="aa95f207798dfdb4" />
        <bindingRedirect oldVersion="5.1.0.0" newVersion="5.2.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by hazzik** [comment]
Updated to 5.2.7 in #453
