### ISSUE TITLE
[RESOLVED] The following types may not be used as proxies

### ISSUE THREAD

**Issue by Pablohack** [nhibernate/fluent-nhibernate#433]
I am programming the connection to the database for a api in net core. I decided to inhibit but I can not connect to the mysql database, it's a local configuration, what I have is the following

that is my CreateSessionFactory

              ` private static ISessionFactory CreateSessionFactory()
                         {
                        try
                         {
                           var dbServer = "w10pmoragantb";
                         var dbUsername = "root";
                        var dbName = "equalsbd";
                        var dbPassword = "123456";
                          var ormAssembly = "SessionNHibernate";

                var config = Fluently.Configure()
                    .Database(MySQLConfiguration
                                  .Standard
                                  .ConnectionString(cs => cs
                                                              .Server(dbServer)
                                                              .Database(dbName)
                                                              .Username(dbUsername)
                                                              .Password(dbPassword)).ShowSql())
                    .Mappings(
                        x =>
                        x.FluentMappings.AddFromAssemblyOf<SessionNHibernate>()).BuildConfiguration();

                return config.BuildSessionFactory();
            }
            catch(Exception ex)
            {

                Console.WriteLine("El error es :" + ex.Message);
            }

            return null;
        }
`

when try connect gives this error

`The following types may not be used as proxies:
EqualsApi.Models.Entities.Usuarios: method set_idUsuarios should be 'public/protected virtual' or 'protected internal virtual'
EqualsApi.Models.Entities.Usuarios: method set_Usuario should be 'public/protected virtual' or 'protected internal virtual'
EqualsApi.Models.Entities.Usuarios: method set_Password should be 'public/protected virtual' or 'protected internal virtual'
EqualsApi.Models.Entities.Usuarios: method set_Perfiles_idPerfiles should be 'public/protected virtual' or 'protected internal virtual'`

and this is my entities

                 `   public class Usuarios 
                  {
                           public virtual long idUsuarios { get; private set; }
                           public virtual string Usuario { get; private set; }
                        public virtual string Password { get; private set; }
                          public virtual string Perfiles_idPerfiles { get; private set; }

                       public static List<Usuarios> ListaUsuario() {

            using (var session = SessionNHibernate.OpenSession() )
            {
                return session.Query<Usuarios>().ToList();
            }
        }
    }`

I've been trying for a long time and I'm new to nhibernate please help

**Comment by Pablohack** [comment]
the first change I made was to modify

    private static ISessionFactory sessionFactory = null;
by

    private static ISessionFactory _sessionFactory = null;
to prevent confusions

the second was to update the usermap by changing its private property to protected, this being private for some reason does not allow the connection to read the attributes

leaving in this way

this

 public class Usuarios 
{
    public virtual long idUsuarios { get; private set; }
    public virtual string Usuario { get; private set; }
    public virtual string Password { get; private set; }
    public virtual string Perfiles_idPerfiles { get; private set; }

   public static List<Usuarios> ListaUsuario() {

        using (var session = SessionNHibernate.OpenSession() )
        {
            return session.Query<Usuarios>().ToList();
        }
    }
}
by the correct way

  public class Usuarios 
{
    public virtual long idUsuarios { get; protected set; }
    public virtual string Usuario { get; protected set; }
    public virtual string Password { get; protected set; }
    public virtual string Perfiles_idPerfiles { get; protected set; }

   public static List<Usuarios> ListaUsuario() {

        using (var session = SessionNHibernate.OpenSession() )
        {
            return session.Query<Usuarios>().ToList();
        }
    }
}
with this your connection to mysql will work or with any other database

**Comment by hazzik** [comment]
General NHibernate question which is more suitable to the StackOverflow/[nhusers group](https://groups.google.com/forum/#!forum/nhusers). Closing as not an issue.

**Comment by hazzik** [comment]
The exception gives exact details what you needed to do, precisely to mark all your properties as virtual. This is a requirement for using proxy feature of NHibernate.
