### ISSUE TITLE
IdentityGenerationStrategyBuilder.Foreign() shouldn't take a string

### ISSUE THREAD

**Issue by drguildo** [nhibernate/fluent-nhibernate#435]
Considering that the main benefit of this project is supposed to be ease of refactoring and other benefits that come with encoding the mappings in the type system, the fact I have to specify the class I want to derive a primary key from as a string. It forces me to use hacks such as:

```cs
Id(x => x.Id).GeneratedBy.Foreign(nameof(StaffMember));
```

to get some degree of type checking.

Why can't I specify it as a generic type parameter?

**Comment by drguildo** [comment]
It looks like the string is the name of the property that maps to the other class. It took me forever to figure this out because the documentation and error messages are so bad. My original point still stands though but maybe there's no way around that.

**Comment by hazzik** [comment]
Yes, the argument of foreign generator is a property, not a class. Closing as not an issue.
