### ISSUE TITLE
If mapping assemblies not specified nhibernate doesn't throw exception

### ISSUE THREAD

**Issue by anton-martynyuk** [nhibernate/fluent-nhibernate#440]
When I Fluently.Configure with fluent nhibernate I register mapping assemblies.
If I make a mistake in the name of mapping assembly and try to select something with Query or 
QueryOver - I receive empty result. It's really a problem - I need to guess whether there is no data returned from Db or mapping is not loaded.
Can you please throw an Exception while creating Fluently.Configure or while selecting data if no mapping where specified?

**Comment by hazzik** [comment]
Querying un-mapped classes will throw in 5.4 of NHibernate (or whatever version will be after 5.3.x). In case of FNH it is totally legit to have empty mappings. Closing as external issue.
