### ISSUE TITLE
fluentnhibernate.org Points To a 1map.com

### ISSUE THREAD

**Issue by bethmaloney** [nhibernate/fluent-nhibernate#445]
Hi, fluentnhibernate.org which is shown in the top bar of the repo now redirects to a third party site.

**Comment by dawncold** [comment]
no need for a official website?

**Comment by crumdev** [comment]
It has been 6 months and is still happening. This should be taken down if it is not going to be fixed.

**Comment by hazzik** [comment]
It happens.
