### ISSUE TITLE
Cache issue-.net core 3.0-Could not load type 'System.Web.Caching.CacheItemPriority' 

### ISSUE THREAD

**Issue by nambir** [nhibernate/fluent-nhibernate#447]
**Inner Exception**
Could not load type 'System.Web.Caching.CacheItemPriority' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.":"System.Web.Caching.CacheItemPriority

**Exception
![nhibernate cache issue](https://user-images.githubusercontent.com/16057911/71021957-5d3ce580-2125-11ea-88cf-e9fe5cdadbbd.jpg)
**
{"An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.\r\n\r\n

**Comment by hazzik** [comment]
`SysCacheProvider` is not supported on .NET Core. Please use one of other available caches: https://github.com/nhibernate/NHibernate-Caches
