### ISSUE TITLE
Assembly is no longer Strong Named

### ISSUE THREAD

**Issue by HudsonAkridge** [nhibernate/fluent-nhibernate#450]
Re-opening the issue raised in #336

Not supporting Strong Naming creates an issue for businesses or projects who use strong naming to enforce signed assembly verification, and/or who want to put their libraries in the GAC (they still exist :) ).

Pull request to resolve this, incoming.

**Comment by jagregory** [comment]
Prior discussions:

- https://github.com/FluentNHibernate/fluent-nhibernate/issues/295
- https://github.com/FluentNHibernate/fluent-nhibernate/issues/342
- https://github.com/FluentNHibernate/fluent-nhibernate/issues/336

Given the low activity of this project what are the consequences of not merging this? I'm in no position to merge this on behalf of anyone else here, so I'm reluctant to merge something people have been historically uncomfortable with.

**Comment by HudsonAkridge** [comment]
Understood James, that's a reasonable concern. :) 

The solution that is on PR #451 adds it as a separate project, so the main project remains unaffected and is not strongly signed, but there's a strong-signed version of FNH that can be published for people that need the strong-assembly-naming to be in place.

This is how [StackExchange.Dapper does it.](https://github.com/StackExchange/Dapper/blob/master/Dapper.StrongName/Dapper.StrongName.csproj) Hopefully that's enough of a compromise to bridge the gap between the two sides of the debate on this.

This [comment from chester89](https://github.com/FluentNHibernate/fluent-nhibernate/issues/342#issuecomment-216767617) seems to indicate that the above implementation would be a preferable solution.
