### ISSUE TITLE
FluentNHibernate ManyToOnePart mapping : PropertyAccessException Invalid Cast

### ISSUE THREAD

**Issue by Karine-GitHub** [nhibernate/fluent-nhibernate#455]
I'm new to NHibernate and I need your help.

Basically, I took a collection named Patient, mapped to **Patient entity**, and splitted it to two collection on different database/server, **S1.DB1.Patient**, mapped to **OtherDataPatient entity**, and **S2.DB1.Patient**, mapped to **ConfidentialDataPatient entity**

My **Patient entity** is also a model for my app. I don't want to touch it to avoid impact on UI. It inherits from **IOtherDataPatient interface** and **IConfidentialDataPatient interface**. Disease entity/model (**S1.DB1.Disease**) have a reference to a patient, and Patient have a mutliple reference to disesase.

Patient 1 --> Disease N

So when I load my collection of diseases, in fact, NHibernate have to load patient from **S1.DB1.Patient** but the type mismatched and I get a `Hibernate.PropertyAccessException : Invalid Cast (check your mapping for property type mismatches)`

How can I force NHibernate to cast it ? I have implemented the implicit cast operator, try to force it in the mapping with .Class<OtherDataPatient>() or explicit cast

Nice to have :

And how can I handle the ConfidentialPatientData data retrieving into the other server during the OtherPatientData data loading ? Is it possible to provide some custom code to execute to NHibernate ?

**Comment by hazzik** [comment]
It is not clear what you're asking here. Is it a bug? A feature request?
