### ISSUE TITLE
.Net Core 3.x

### ISSUE THREAD

**Issue by SigmaSoftSol** [nhibernate/fluent-nhibernate#456]
Hello Team,
   When Can we expect the Fluent NHibernate for .Net 3.x.

Thanks & Regards,
Seshu Kumar.

**Comment by chester89** [comment]
@SigmaSoftSol do you have a specific error, code sample or a stacktrace?

**Comment by SigmaSoftSol** [comment]
No I donot Have any issues, but I would like to know the release of the FulentNhibernate with .Net core 3.1

**Comment by douglas2** [comment]
I am using FluentNHibernate 2.1.2 with NHibernate 5.3.2 in my ASP.NET Core 3.1 with no issues.

**Comment by hazzik** [comment]
It should work with any .NET Core version above 2.0. Please report any specific issues.
