### ISSUE TITLE
"@" character in the password at Azure sql causes error

### ISSUE THREAD

**Issue by zbak** [nhibernate/fluent-nhibernate#481]
while the @ character is in a Azure SQL db password, the fluent api configuration fails.

My code example:
```csharp
            var configuration = Fluently.Configure()
                .Database(MsSqlConfiguration.MsSql2012.ConnectionString(connectionStringwith_at_inpassword)
                    .Driver<SqlAzureClientDriver>())
                .Mappings(m => m.HbmMappings.AddFromAssembly(currentAssembly)).BuildConfiguration();
```

**Comment by hazzik** [comment]
What's the error?

**Comment by zbak** [comment]
Sorry, it is the '', not the "@".

so, if the connection string is: 
var connectionString = "Server=________.database.windows.net;database=Betting;User Id=_______;Password=FggfFgggh123@''";
The error is: 
InnerException {"El formato de la cadena de inicialización no se ajusta a la especificación que comienza en el índice 73."}   System.Exception {System.ArgumentException} (Sorry, I live in Madrid) the 73. character is the start of the Password tag.

But if I remove the last 2 chars at from the password at Azure, and change my password to:
var connectionString = "Server=________.database.windows.net;database=Betting;User Id=_______;Password=FggfFgggh123@";
It works fine

**Comment by zbak** [comment]
Just to be more accurete on the character: 
Console.WriteLine((char)39);

**Comment by hazzik** [comment]
And what is the stack trace?

**Comment by hazzik** [comment]
Enquote your password like this:

```csharp
 var connectionString = "Server=________.database.windows.net;database=Betting;User Id=_______;Password=\"FggfFgggh123@''\"";
```

**Comment by zbak** [comment]
Thank you very much!
Agh, I could hit my head against a wall, sorry for wasting your time.
