### ISSUE TITLE
how to using Microsoft.Data.SqlClient fluent-nhibernate 

### ISSUE THREAD

**Issue by rogeryamato** [nhibernate/fluent-nhibernate#488]
Is fluent-nhibernate can use Microsoft.Data.SqlClient?

And how to use it..

I see in this issue https://github.com/nhibernate/nhibernate-core/pull/2216 has fix it, But how about for fluent-nhibernate?

Thanks.

**Comment by gliljas** [comment]
Fluent NHibernate is used for mapping and doesn't care how NHibernate connects to the database.

**Comment by jornhd** [comment]
You need to add **.Driver<MicrosoftDataSqlClientDriver>()** in the configuration:

```
Fluently.Configure()
    .Database(
        MsSqlConfiguration.MsSql2012
            .Driver<MicrosoftDataSqlClientDriver>()
            .ConnectionString(connectionString)
    )
    .Mappings(...)
    .BuildSessionFactory();
```
