### ISSUE TITLE
Upgrading to 3.1.0 brakes UTC-DateTime-Convention

### ISSUE THREAD

**Issue by 1234Georg** [nhibernate/fluent-nhibernate#498]
I am using fluent nHibernate with SQLite. And I am working with UTC-DateTime in my code. 
I added "DateTimeKind=Utc" to my sqllite connection string, and I am telling nHibernate that it should use UTC (IPropertyInstance.CustomType<UtcDateTimeType>())

These are my package refs
```
	<ItemGroup>
		<PackageReference Include="FluentNHibernate" Version="3.1.0" />
                <PackageReference Include="Microsoft.Data.Sqlite" Version="5.0.5" />
                <PackageReference Include="NHibernate.Caches.CoreMemoryCache" Version="5.7.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
	</ItemGroup>
```
This is my convention for UTC
```
    public class DateTimeAsUtcPropertyConvention : IPropertyConvention
    {
        public void Apply(IPropertyInstance instance)
        {
            if (instance.Type.Name == typeof(DateTime).Name || instance.Type.Name == typeof(DateTime?).Name)
            {
                instance.CustomType<UtcDateTimeType>();
            }
        }
    }
```
I had fluent-nhibernate 3.0.1 installed, which worked as expected: I am saving and getting a DateTime that has a UTC-kind and the correct date and time.
When I upgrade fluent-nHibernate to 3.1.0 that doesn't work any more. I am saving UTC DateTime, but I get my local time with kind UTC.

Any ideas on this?

**Comment by hazzik** [comment]
Please see here: https://github.com/nhibernate/nhibernate-core/pull/1378

From documentation:

> Due to [behavior of System.Data.SQLite](https://system.data.sqlite.org/index.html/tktview/44a0955ea344a777ffdbcc077831e1adc8b77a36) with `DateTime`, consider using `DateTimeFormatString=yyyy-MM-dd HH:mm:ss.FFFFFFF;` in the SQLite connection string for preventing undesired time shifts with its default configuration.
