### ISSUE TITLE
Error after version update

### ISSUE THREAD

**Issue by LendaUrbana** [nhibernate/fluent-nhibernate#504]
After I update fluent nhibernate and nhibernate I started getting the message below at mapping time.

"Column 'SQL_TYPE_NAME' does not belong to table Data Types."

Fluent Nhibernate Old Version  : 2.1.2
Nhibernate Old Version  : 5.2.0

Code :

       var cfg = new Configuration();
                cfg.DataBaseIntegration(x =>
                {
                   
                    x.ConnectionString = ConnectionString.get(serverConexao.tipo)
                    x.Dialect<DB2400Dialect>();
                    x.Driver<DB2400Driver>();
                    x.LogSqlInConsole = true;
                    x.LogFormattedSql = true;
                    x.BatchSize = 5000;
                    x.PrepareCommands = true;
                    x.Timeout = 0;
                });
                factory = Fluently.Configure(cfg)
                    .ExposeConfiguration(config => new SchemaExport(cfg).Create(false, false))
                    .Mappings(c => c.FluentMappings.AddFromAssembly(Assembly.GetExecutingAssembly()))
                    .BuildSessionFactory();

**Comment by bahusoid** [comment]
See #3438
