### ISSUE TITLE
MSSQL is up to version 2019, but the configurations only support up to version 2012

### ISSUE THREAD

**Issue by alejandromoncayo** [nhibernate/fluent-nhibernate#510]
On the file: https://github.com/nhibernate/fluent-nhibernate/blob/master/src/FluentNHibernate/Cfg/Db/MsSqlConfiguration.cs
the max version is MsSql2012, but MSSQL is up to version 2019 at the moment of this post:
https://docs.microsoft.com/en-us/troubleshoot/sql/general/determine-version-edition-update-level

**Comment by fredericDelaporte** [comment]
There are no newer configuration because there are currently no need for it. We only add newer dialects when we need to support some new features of newer SQL versions. MsSql2012 dialect works with any newer SQL version.
