### ISSUE TITLE
Issue while using "SQLAnywhere17" Fluent nhibernate

### ISSUE THREAD

**Issue by sravangontla** [nhibernate/fluent-nhibernate#517]
### Discussed in https://github.com/nhibernate/fluent-nhibernate/discussions/516

<div type='discussions-op-text'>

<sup>Originally posted by **sravangontla** January 12, 2022</sup>
Hi Team,
  I am unable to perform DML operations using Fluent nhibernate. 

**Code :** 

                var sessionFactory = CreateSessionFactory();
                using (var session = sessionFactory.OpenSession())
                {
                    using (var transaction = session.BeginTransaction())
                    {
                        var newObject = new model{  };
                        session.SaveAsync(newObject);

                        transaction.Commit();
                    }
                }

**Error Details :**
  Error raised while calling transaction.commit() statement. And respective error is "System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Data.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.' "

Env:
  netcoreapp3.1
  FluentNHibernate =>    Version="3.1.0"  

Thanks,
Sravan G
 

 </div>

**Comment by hazzik** [comment]
There's no .NET core compatible provider for SAP Sql Anywhere 17.

**Comment by hazzik** [comment]
No need to duplicate things.
