### ISSUE TITLE
FIPS-related error on FIPS 140 enabled Windows system

### ISSUE THREAD

**Issue by UsgsMonkey** [nhibernate/fluent-nhibernate#524]
We're experiencing the following error when running our fluent-nhibernate enabled ORM on a FIPS 140 enabled Windows server ...

```
FluentNHibernate.Cfg.FluentConfigurationException HResult=0x80131500 Message=An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.

Source=FluentNHibernate StackTrace: 
at FluentNHibernate.Cfg.FluentConfiguration.BuildSessionFactory()
at Markup.Global.<>c.b__6_0(IComponentContext _) in D:\Code\markup-app-test\src\Markup\Global.asax.cs:line 117
at Autofac.RegistrationExtensions.<>c__DisplayClass5_01.<Register>b__0(IComponentContext c, IEnumerable1 p)
at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_01.<ForDelegate>b__0(IComponentContext c, IEnumerable1 p)
at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable1 parameters) at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable1 parameters, Object& decoratorTarget)
```

This exception was originally thrown at this call stack: [External Code]

Inner Exception 1: TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2: InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

We referenced the latest Fluent NHibernate (3.1.0) and NHibernate (5.3.3) in Visual Studio 2019 (16.11.8), but still are receiving this error.  Any insight and/or hope for remediation on this issue would be wonderful and very appreciated!

Please see this discussion [post ](https://github.com/nhibernate/fluent-nhibernate/discussions/523) for context.

Regards,

Brett, Nguyet, Abby, and the USGS Hydro Tools dev team.

**Comment by oskarb** [comment]
It looks like the stack trace is only showing non-NHibernate parts. I think you should add the full stack traces from the inner exceptions, in particular the parts coming from inside (or below) NHibernate or FluentNHibernate.

**Comment by UsgsMonkey** [comment]
Ok I'll ask Nguyet to get that detail.

**Comment by oskarb** [comment]
> Ok I'll ask Nguyet to get that detail.

A simple ToString() on the top-level exception *normally* includes messages and stack traces from all inner exception. That's may be a good starting point, even if you want to manually edit out any sensitive parts before posting.

**Comment by toihoc1997** [comment]
This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

Source Error:


Line 68:             try
Line 69:             {
Line 70:                 return Fluently.Configure()
Line 71:                     .Database(PostgreSQLConfiguration.PostgreSQL82
Line 72:                     .ConnectionString(c => c.FromConnectionStringWithKey("test"))

Source File: D:\Global.asax.cs    Line: 70



Stack Trace:


[InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.]
   System.Security.Cryptography.MD5CryptoServiceProvider..ctor() +12350168

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +328
   System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args) +781
   System.Security.Cryptography.MD5.Create() +20
   Npgsql.<AuthenticateMD5>d__3.MoveNext() +84
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   Npgsql.<Authenticate>d__0.MoveNext() +870
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   Npgsql.<Open>d__175.MoveNext() +2584
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   Npgsql.<OpenNewConnector>d__41.MoveNext() +551
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   Npgsql.<<Rent>g__RentAsync|0>d.MoveNext() +462
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   Npgsql.<<Open>g__OpenAsync|0>d.MoveNext() +2249
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   Npgsql.NpgsqlConnection.Open() +56
   NHibernate.Connection.DriverConnectionProvider.GetConnection(String connectionString) +183
   NHibernate.Connection.ConnectionProvider.GetConnection() +27
   NHibernate.Tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.Prepare() +14
   NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.GetReservedWords(Dialect dialect, IConnectionHelper connectionHelper) +37
   NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.Update(ISessionFactoryImplementor sessionFactory) +55
   NHibernate.Impl.SessionFactoryImpl..ctor(Configuration cfg, IMapping mapping, Settings settings, EventListeners listeners) +664
   NHibernate.Cfg.Configuration.BuildSessionFactory() +173
   FluentNHibernate.Cfg.FluentConfiguration.BuildSessionFactory() +41

[FluentConfigurationException: An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.

]
   FluentNHibernate.Cfg.FluentConfiguration.BuildSessionFactory() +61
   USGS.NGTOC.HydroMaintenance.MvcApplication.CreateSessionFactory() in D:\Global.asax.cs:70

[ApplicationException: An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.

]
   USGS.NGTOC.HydroMaintenance.MvcApplication.CreateSessionFactory() in D:\Global.asax.cs:96
   USGS.NGTOC.HydroMaintenance.MvcApplication.Application_Start() in D:\Global.asax.cs:34

[HttpException (0x80004005): An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.

]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +475
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +176
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +220
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +303

[HttpException (0x80004005): An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.

]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +659
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +89
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +188

**Comment by oskarb** [comment]
System.Security.Cryptography.MD5.Create() +20
Npgsql.d__3.MoveNext() +84

So at least this particular problem is not NHibernate but the PostgreSQL library using MD5.

Is there something in the connection string causing this? Or that could be put in the connection string to prevent it?

Or is this a matter of your PostgreSQL server being configured to use MD5, and the NPGSQL client library picking up on that?

I would suggest first checking you PostgreSQL configuration to see if there is something to explain this, and if not, to raise a discussion with the npgsql developers (https://www.npgsql.org/).

**Comment by oskarb** [comment]
Might be relevant:
https://www.postgresql.org/docs/14/auth-password.html
https://github.com/npgsql/npgsql/pull/1769

**Comment by fredericDelaporte** [comment]
So, up to this point, the issue would be an external issue, currently either rooted in Npgsql or in your own connection string / database configuration.

But maybe you would have other failures after solving this one, which could then be in NHibernate.

Feel free to reopen this issue if that is the case, providing the details about the new exception.

(As stated in this [post](https://stackoverflow.com/a/33356819), you are entering a painful process with this activation of "FIPS 140" compliance mode on Windows.)

**Comment by gliljas** [comment]
This is where things go south in NPGSQL

https://github.com/npgsql/npgsql/blob/0f45fb1915e492313ff2045588b817121503f7de/src/Npgsql/Internal/NpgsqlConnector.Auth.cs#L263

**Comment by UsgsMonkey** [comment]
Thanks guys - we appreciate your helpful responses and thoughts.
