### ISSUE TITLE
ForeignKey.EndsWith messes up multiple one-to-many relationships

### ISSUE THREAD

**Issue by jagregory** [nhibernate/fluent-nhibernate#57]
Dear FluentNHibernate developers,

I recently had and issue with Fluent, which involved two one-to-many relationships between the same two entities. (the [details are on SO](http://stackoverflow.com/questions/2777152/fluentnhibernate-multiple-one-to-many-relationships-between-the-same-entities).)
I always had ForeignKey.EndsWith("Id") within my convention collection, because I thought it was a very elegant way of expressing what I want.

The problem is, that when I have multiple many-to-one relationship between the same entites, Fluent can't figure out which property maps to which collection, but this is the least of the problems.
I set up a HasManyConvention and a ReferenceConvention (attached), in which I provided some logics about how to do it.

This is where things got messy: with ForeignKey.EndsWith, it actually created a third column for one of the entities, and the relationships didn't work. So in the end, I tried putting the naming into the HasMany and Reference conventions, and it just worked. I honestly don't know if this is by design or just an error, but for other people experiencing the same issue, it would be helpful if you wrote it in the wiki that it isn't working well in such scenarios.

Yours sincerely,
Timur Kristóf

**Comment by chester89** [comment]
Fixed in [PR 250] (https://github.com/jagregory/fluent-nhibernate/pull/250). Still doesn't have any tests - shame on me, I should think of something
