### ISSUE TITLE
Microsoft.Data.Sqlite with latest fluentnhibernate - update of tables not working 

### ISSUE THREAD

**Issue by PriyankaChandrabose** [nhibernate/fluent-nhibernate#622]
```csharp
_sessionFactory = Fluently.Configure()
  .Database(
    MsSqliteConfiguration.Standard
      .ConnectionString(c => c.Is($"data source={_dbFilePath};"))
      .Dialect<NHibernate.Extensions.Sqlite.SqliteDialect>()
      .Driver<NHibernate.Extensions.Sqlite.SqliteDriver>()
    )
  .Mappings(m => m.FluentMappings.AddFromAssemblyOf())
  .ExposeConfiguration(BuildSchema).BuildSessionFactory();
```

When schema update is being called, the following exception came with or with out actual schema update

```
ERROR NHibernate.Tool.hbm2ddl.SchemaUpdate - could not complete schema update
System.ArgumentException: More restrictions were provided than the collection 'Tables' supports.
at Microsoft.Data.Sqlite.SqliteConnection.GetSchema(String collectionName, String[] restrictionValues)
at NHibernate.Dialect.Schema.AbstractDataBaseSchema.GetTables(String catalog, String schemaPattern, String tableNamePattern, String[] types)
at NHibernate.Dialect.Schema.SQLiteDataBaseMetaData.GetTables(String catalog, String schemaPattern, String tableNamePattern, String[] types)
at NHibernate.Tool.hbm2ddl.DatabaseMetadata.GetTableMetadata(String name, String schema, String catalog, Boolean isQuoted)
at NHibernate.Cfg.Configuration.GenerateSchemaUpdateScript(Dialect dialect, IDatabaseMetadata databaseMetadata)
at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)
```

**Comment by hazzik** [comment]
Thanks. I don't really know what is `Hibernate.Extensions.Sqlite.SqliteDialect`. I'll take a look at the issue later in the week.

**Comment by PriyankaChandrabose** [comment]
To use nhibernate with Microsoft.data.sqlite to support creation and updation of tables - what driver and dialect to be used ?
any examples available ?

**Comment by PriyankaChandrabose** [comment]
Hi,

Found the exact point of the error 
![GetSchema](https://github.com/nhibernate/fluent-nhibernate/assets/68009852/339d7f82-53e2-4e3d-b256-4d7c3397d710)
![MethodCall](https://github.com/nhibernate/fluent-nhibernate/assets/68009852/4b5235bd-cbbc-44a7-8342-341526695f6c)
![GetTables](https://github.com/nhibernate/fluent-nhibernate/assets/68009852/8a96f31f-c847-4198-ad59-48413f3562f0)


GetTables method of nhibernate is passing second argument and sqlconnection.cs class of Microsoft.Data.Sqlite is throing exception is 2nd argument is passed

**Comment by fredericDelaporte** [comment]
So, it looks like Microsoft.Data.Sqlite simply does not support a feature required by NHibernate for schema-update. The easier way to solve this is to ask for the feature on Microsoft side, if you find where to ask. But it seems they do not intend implementing it due to how they [document this lack of support](https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/adonet-limitations#database-schema-information).

> `DbConnection.GetSchema()` isn't implemented. This API isn't well-defined, so we recommend retrieving database metadata directly using standard SQLite APIs like the [sqlite_master](https://www.sqlite.org/fileformat.html#storage_of_the_sql_database_schema) table and the [table_info](https://www.sqlite.org/pragma.html#pragma_table_info) PRAGMA.
>
>For more information, see [Metadata](https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/metadata#schema-metadata).

On that later link:

> Microsoft.Data.Sqlite doesn't implement the GetSchema method on DbConnection. Instead, you can query directly for schema information using the [sqlite_master](https://www.sqlite.org/fileformat.html#storage_of_the_sql_database_schema) table and PRAGMA statements like [table_info](https://www.sqlite.org/pragma.html#pragma_table_info) and [foreign_key_list](https://www.sqlite.org/pragma.html#pragma_foreign_key_list).

So, your other option is to implement your own `SQLiteDataBaseMetaData` following the recommendations of the above documentation.
