### ISSUE TITLE
Add .NET 6/8 as target framework

### ISSUE THREAD

**Issue by SymbioticKilla** [nhibernate/fluent-nhibernate#679]
Hi,

is it possible to add supported .NET version?

Thanks!

**Comment by hazzik** [comment]
To do exactly what?

**Comment by SymbioticKilla** [comment]
Sorry, my bad! It was little bit complicated as I thought:
![image](https://github.com/nhibernate/fluent-nhibernate/assets/59652865/1dfc7940-404d-4658-ab28-801dd4e150d5)
I need to reference extra newest [iesi.collections](https://github.com/nhibernate/iesi.collections)
Because nhibernate uses wildcards and 4.0.4 is minimal version, which will be automatically taken. This version ist .NET Standard 1.6.

**Comment by oskarb** [comment]
> Ok, now is Antlr3.Runtime the problem:

What is it that is the actual problem?

**Comment by SymbioticKilla** [comment]
It produces huge package lock with .NET Standard in it and security tools find false positives.

**Comment by hazzik** [comment]
Unfortunately, adding .NET 6/8 build would not solve the problem mentioned. I would probably add the builds later, but not for this exact reason.
