### ISSUE TITLE
Postgres PascalCase naming issue

### ISSUE THREAD

**Issue by samelson1** [nhibernate/fluent-nhibernate#699]
Hi guys,

I appreciate the work you do on these projects. I am currently in the process of migrating SQL Server to Postgres. I have converted my database fine and all the tables and columns have the correct names which are PascalCase. I can even connect and get data in my system as I have written a custom naming convention provider so that it preserves the casing.

My issue lies with SchemaUpdate. I have debugged the code and it doesn't seem to recognise quoted table names to apply schema changes. It tries to just recreate each table, I have been playing around and I was able to get it to see the tables by not quoting the table names, however this just causes other issues.

![image](https://github.com/nhibernate/fluent-nhibernate/assets/28952359/7e6b4964-bf6b-44a9-840a-dc167aa59c26)

The image above is the method Configuration.GenerateUpdateSchemaScript. The "databaseMetadata.GetTableMetadata" is returning null when quoted table named are passed, and changing the "table.IsQuoted" doesn't seem to make a difference. 

Before I dig even further into the code I am wondering if this is a restriction you're aware of?

Also wasn't sure if this should go here on in the nhib core repo, so let me know if I need to ask over there.

Cheers.

**Comment by hazzik** [comment]
It is really hard to answer anything without seeing any code.

**Comment by samelson1** [comment]
Hey yeah sorry about that. Here is my config:
![image](https://github.com/nhibernate/fluent-nhibernate/assets/28952359/451a1c7d-90d0-476b-af4a-a64cf8cba3fb)

Naming strategy:
![image](https://github.com/nhibernate/fluent-nhibernate/assets/28952359/e94e6aa5-dc07-4986-9898-d57b51d35675)

and then the issue I am having is with trying to update the schema:
![image](https://github.com/nhibernate/fluent-nhibernate/assets/28952359/2f7b7ca2-aece-48bf-b303-e302e3abc7d5)

Please let me know if I can provide further information.

**Comment by hazzik** [comment]
You're mixing NHibernate's mapping by code (`INamingStrategy`) and FluentNHibernate, this is why it does not work. `INamingStrategy` is just ignored.

**Comment by samelson1** [comment]
It does seem to use INamingStrategy though as it's being hit and changes the table names and columns, otherwise they are all lowercase. How would you advise I go about this?

**Comment by samelson1** [comment]
@hazzik  If this is out of scope of what you'd normally resolve would you be willing to accept a donation to help us resolve this?

**Comment by hazzik** [comment]
Ok, I misunderstood the `INamingStrategy`. It is not a part of mapping by code, it is some ancient mechanism in the NHibernate itself. It operates last before mapping is bound to the model. In theory your code should work. Although you need to modify `ClassToTableName` method to convert from full class name to table name (eg use `StringHelper.Unqualify(className)`).

What version of NHiberante and FluentNHibernate do you use?

**Comment by samelson1** [comment]
So the code mostly works, it just seems to be this UpdateSchema mechanism that is broken. It's unable to get the table meta-data so it just sees it as not existing and tries to recreate it. 

Nhibernate v5.5.1
Fluent Nhibernate v3.3.0

This didn't seem to make a difference unfortunately.

![image](https://github.com/nhibernate/fluent-nhibernate/assets/28952359/621f5250-9a4c-4242-8d72-6c9af9615ace)

When I debug the table name looks as below, although tableMetaData seems to be null always. When I debugged this through with SQL server it was finding some meta data and then adding the relevant alter strings.

![image](https://github.com/nhibernate/fluent-nhibernate/assets/28952359/ecf89df7-6700-4412-98a5-c093774d1a2d)

**Comment by samelson1** [comment]
I did also manage to get the tableMapping.IsQuoted to be true but that didn't seem to make a difference.

**Comment by samelson1** [comment]
How it looks in the database: 
![image](https://github.com/nhibernate/fluent-nhibernate/assets/28952359/594b9e46-a47f-4f47-8b08-17ace1acb163)

**Comment by hazzik** [comment]
You need to add something like following into your mapping configuration
```csharp
.FluentMappings.Conventions.Add(
    ConventionBuilder.Class.Always(c => c.Table($"\"{c.EntityType.Name}\"")),
    ConventionBuilder.Property.Always(p => p.Column($"\"{p.Name}\"")) // , ...etc
);
```
This goes inside the lambda that you pass as a second parameter to `CompileConfiguration`.
And remove `INamingStrategy`.

**Comment by samelson1** [comment]
Hey thanks so I am definitely making progress. It seems to mostly create the tables and columns correctly although I am having a few issues atm. Here is my config:

![image](https://github.com/nhibernate/fluent-nhibernate/assets/28952359/95661a4f-ea87-415a-a348-dd3c623b1215)

Issue 1, random columns called system.action created:

![image](https://github.com/nhibernate/fluent-nhibernate/assets/28952359/34635f95-7964-4166-9d4c-d74957303aad)

Issue 2, it doesn't seem to be changing column names for many to many mappings, and I can't see anywhere how to do it under the many to many section:

![image](https://github.com/nhibernate/fluent-nhibernate/assets/28952359/0d480a35-6d0b-4a49-9078-9a0d5d9d6b8c)

Issue 3, it seems unable to be able to create audit table:

![image](https://github.com/nhibernate/fluent-nhibernate/assets/28952359/1ec5ea86-1bea-4fd8-a551-410824b8ddfb)

I really appreciate your help on the matter!

**Comment by samelson1** [comment]
I basically ended up having to pull up most of the schema updating processes and making some changes manually. Thanks for your help though!
