### ISSUE TITLE
Defining a CustomType for KeyReference in CompositeId()

### ISSUE THREAD

**Issue by m4cx** [nhibernate/fluent-nhibernate#78]
Hey Guys, 

I opened this topic within stackoverflow already, but until now there is no answer. Maybe you can have a look:

http://stackoverflow.com/questions/6827154/mapping-compositeid-keyreference-on-interface

Thanks.

**Comment by Sebazzz** [comment]
You're right, there is currently no support. To make matters worse, Fluent NHibernate *does* set the `class` attribute in the mapping, causing NHibernate to *ignore* entity-name. This causes mapping to any interface to fail. 

My current workaround was to export the mapping to XML (using `ExportTo`), then using the XML mappings from the classes I couldn't properly map in code. 

In short:
1. Fluent NHibernate should not set the *class* attribute unless specifically asked by the user. This is not something that could be done in a minor release as it can break working code.
2. Allow specifying the `class` of a KeyReference (`key-many-to-one` in XML).
